Date: 05April2022
Program to take input, using input and swapping
Example of multiple assignment

In [ ]:
#Program to add two numbers
num1=int(input("Enter integer :"))
num2=int(input("Enter integer :"))
sum=num1+num2
print("Sum is :",sum)

In [ ]:
# Example of multiple assignment

a=10
b=20
a,b=b+2,a+3
print("a =",a)
print("b =",b)

In [ ]:
#Few statements using if
if 2<1:
  print("First")
elif:
  print("Second")

If else statements 
Date: 07April2022


In [ ]:
#Few statements use switch if condiotions
a=20
b=30
if(a<b):
  print(a,"<",b)
elif(a==b):
  print(a,"=",b)
else:
  print(a,">",b)

In [ ]:
#Singleline statement written in multiline

a=\
10\
+20
a

In [ ]:
#Singleline statement written in multiline
print("Hello"\
      "Hi")

In [ ]:
#Multiline statement which are supposed to be single line
a=10*20\
30-4
a

In [ ]:
#two statements written in single line
a=7 ;print(a)

In [ ]:
#Multi line in single line
if 2>1: print("2")

In [ ]:
#Put a blank line
if 2>1:
  print("1")
  print("2")
  

In [ ]:
#Using comment
print("Hello world") #This is comment

Hello world


Date : 07 April 2022
Learning to use function

In [ ]:
#Using function in python
def add(a,b):
  return(a+b)
add(10,20)
add("Hi","Run")

'HiRun'

In [ ]:
#Syntax error in program
#Practicing on my own, program for finding a prime number
num=int(input("Enter the integer :"))
m=num/2
flag=0
i=1
while(i<=m):
  if(m%i==0):
    print("Number is not prime")
    flag=1
    i+=2
    break;
if(flag==0):
  print("Number is prime")


DATE: 08april2022
Using single quotes and double quotes

PYTHON QUOTATIONS

In [ ]:
#Using double quotes

print("Hello World")

In [ ]:
#Using single quotes

print('Hello world')

In [ ]:
#Using "\ in multiline comments"

'''Hello world\
\yo'''

print(''' Hello    World ''')

In [ ]:
#Cannot use double quotes within double quotes same with single quotes
#Syntactical error will pop-upt
print("Hello world "I am doing well"")

#Usage of triple quotes

print(""" Hello world 
                      h ey """)

# % operator in print formatting
x="Naive"
print("Hello world I am %s"%(x))

In [ ]:
#Format method in formatting 
x="class"
y=1
print("I have been in the {0} for {1}".format(x,y))

I have been in the class for 1


In [ ]:
#Format method in formatting
print("I have been in the {x} for {printer}".format(x="class",printer=1))

I have been in the class for 1


In [ ]:
# f strings
x=10
printer="HP"
print(f"I just printed {x} pages to the printer {printer}")

I just printed 10 pages to the printer HP


In [ ]:
#del keyword

x=10
del x
print(x)

In [ ]:
#checking variable type

x=10
y="Num"
c=1.3
d=True
e=('a','b')
f=['a','b']
j={"1":"Hello","2":"Bro"}
type(j)

DATE 19 April 2022
**Python lists, data types in python** 

# Data types

Python lists


Date 19April2022

Python lists, slicing in the lists

Fundamental data type : Int, flaot , string,complex

Sequential data type : List,tuple,set,dictionary


List - It can contain different data types
- Values can be changed
Operations which can be performed
Slicing, Indexing


In [ ]:
days=['Mon','Tue','Wed',4,5,6,7]
#slicing of the list
print(days[1:3])
print(days[0:1])
print(days[0:6])

#length of the list
print("Length of the list",len(days))
#Slicing of the list
print(days[0:2])

#Indexing
print(days[2])
#Reassign the value
days[2]="Ayush"
print(days[2])

In [ ]:
#iterating on the list
days=['Mon','Tue','Wed',4,5,6,7]
#Using the for loop 
for n in days:
  print(n)

Multidimensional list 
There will be list inside the list
#Date: 19April2022

In [ ]:
matrix=[[1,2,3,4],[5,6,7,8]]
matrix
#Checking the length of the list
#print(len(matrix))
#print(matrix)
#print(matrix[0:1])
for n in matrix:
    print(m)

Tuple as a data type
Date: 19 April 2022

In [ ]:
subjects=("maths","english","hindi")
subjects
#Slicing
print(subjects[1])
print(subjects[0:2])
#Indexing (Item assingment)
#print(subjects[2])
#subjects[2]="Shubh"
#print(subjects[2])

for n in subjects:
  print(n)

Dictionaries
A dictionary holds key value pairs. Declare it in curly braces, with pairs separated by commas


In [ ]:
person={'City':'Ahemdabad','Age':7}
print(person)

#Accessing a value
print(person['City'])

#List of keys
print(person.keys())

Boolean data type

In [ ]:
#Assigning boolean by using relational operator
num=2>1
print(num)
#Checking condition using relational operator
num=1>2
print(num)


Set in python
date 19 april 2022
Using different functions


With set we can use functions like add and remove


In [ ]:
age=(21,18,32,64)
age

DATE : 22 April 2022


Sets from python data type


In [ ]:
#Set is mutable. You can change its element or add more. Using add() function
#And remove the elements using remove() function.
age={21,18,32,64}
age
age.add(69)
print(age)
age.remove(69)
print(age)
age.add("Ram")
print(age)
age.remove("Ram")
print(age)





Completed sequential data type

In [ ]:
#Python wiht the dynamic typing

#It converts the value into an int
int(42.7)
#Turning a boolean into int 
int(False)

In [ ]:
#Float
#It converts the value into a float

int("77")
float(7)
float(True)
float("11.9")
float("2.1e-4")
#float(2.1e-2)

In [ ]:
#str()
#It converts the value into a string
str(6)
str(7.4)
str(True)
str(89)

In [ ]:
#bool()
#It converts the value

bool(0)
bool(True)
bool(3)
bool(())
bool({})

#Any meaningful value will return a true

False

Date: 22 April 2022



#Date : 22April2022


#Set
#It converts the value into a set

In [ ]:
#set() we use {} to define the list
set({1,2,2,3})

{1, 2, 3}

In [ ]:
#list()
#It converts the value into a list
list("1234")
list({1,2,3,4})
list({"a":1})

['a']

In [ ]:
#Tuple()
#This function converts the value into a tuple

tuple({1,2,3,4})

#Using composite functions

tuple(list(set([1,2])))
list(set({1,2,3}))


#Python local variable
#When you declare a variable in a function, class or so it is scope . If you call it outside of that scope, you get an "Undefinied"


In [ ]:
#Using function

def func():
  #Declaring local variable
  num=2
  print(num)
func()


2


In [ ]:
def add():
  num=10
  num1=20
  print("Sum is",num+num1)
add()
print(num-num2)

Sum is 30


NameError: ignored

In [ ]:
#Global variable
#Declaring global variable
#22April2022
n=8
def add():
  #Declaring local variable
  m=n+2
  print(m)
add()
print(n)


10
8


In [ ]:
#Declaring global variable
n=8
def func():
  global n
  n=0
  n=n+2
  print(n)
func()
print(n)

# Date : 26April2022


Identifier : Identifier is a user-defined name to represent a variable, a function,a class, a module or any other object
- It is a programmable entity in python one with a name
- It is a name given to the fundamental building blocks in a program


Rules for naming valid identifiers in python :
1 - Lowercase letters (a to z)
2 - Uppercase letters (A to Z)
3 - Digits (0 to 9)
4 - Underscore (_)
Some valid names are : 
myVar
_9veriename

In [ ]:
#Program to get all the keywords
#Date : 26April2022
import keyword
keyword.kwlist
keyword.iskeyword("main")

#keyword.iskeyword() to check the given string is keyword or not

#isidentifier() to check if the given string is identifier or not
'__$$__'.isidentifier()

Reserved classes of python identifiers
- Some classes have special meanings
- Reserve classes and reserve modules starts with ("__") and ends with ("__")


In [ ]:
#Overwritting the global variable

num=2
def func():
  num=3
  print(num)
func()

#We can't use the global variable and overwrite with the local variable and 
#print it

#Enclosed scope

In [ ]:
def red():
  num1=1
  def blue():
    num2=2
    print(num1)
    print(num2)
  blue()
  print(num1)
red()

# Date : 29April2022

Enclosed scope in python

- We also declare a variable 'b' outside any other python variable scope, This makes it global scope

In [ ]:
def red():
  num1=1
  def blue():
    num2=2
    print(num1)
    print(num2)
  blue()
  print(num1)
red()

1
2
1


Global keyword 
so far we haven't had any kind of a problem with global scope. So let's take any example


In [ ]:
num=1
def counter():
  num=2
  print(num)

counter()

#Now, when we make a reference to 'num' outside this function, we get 1 
#instead of 2
num

2


1

Global keyword in python
- Why does this happen? well, this is because when we set 'a' to 2. it created a local variable in the local scope of 'counter'
- This didn't change anything for the global 'a'

In [ ]:
a=1
def counter():
  global a
  a=2
  print(a)
counter()

2


Non local keyword in python
- like the 'global' keyword, you want to make a change to a nonlocal variable, you must use the nonlocal keyword. Let's first try this without the keyword

In [ ]:
def red():
  a=1
  def blue():
    a=2
    b=2
    print(a)
    print(b)
  blue()
  print(a)

red()

2
2
1


In [ ]:
def red():
  a=1
  def blue():
    nonlocal a
    a=2
    b=2
    print(a)
    print(b)
  blue()
  print(a)

red()

2
2
2


Decision making statements are evaluation of conditions occuring while execution of the program and specifying actions taken according to the conditions

-Control flow structure
- while writing program, we almost always need the ability to check the condition and then change the course of program, the simplest way to do so is using:
if statement 



In [ ]:
 var1=100
 if var1:
   print("1- Got a true expression value")
   print(var1)
var2=0
if var2:
  print("2- Got a true expression value")
  print(var2)
print("Goodbye")

1- Got a true expression value
100
Goodbye


In [ ]:
#To check, entered number is even or not

num=(int(input("Enter number : ")))
if num%2==0:
  print("Number is even")

Enter number : 2
Number is even


In [ ]:
#Program to print the largest number among three

num1=int(input("Enter number 1 :"))
num2=int(input("Enter number 2 :"))
num3=int(input("Enter number 3 :"))
if num1>num2 and num1>num3:
  print("1 is largest")
if num2>num1 and num2>num3:
  print("2 is largest")
else:
  print("3 is largest")

Enter number 1 :2
Enter number 2 :3
Enter number 3 :1
2 is largest


In [ ]:
#Program of simple if else

Self
Using pointers in python


In [ ]:
y=12
print(&y)

#Date: 13May2022


Python control structure 
- Decision making statement
- Iterative statement

Decision making statement(
  1- Simple if
  2- If else
  3- Nested If
)

Types of loops in python
1- while loop
2- for loop
3- Nested loop


In [ ]:
# while loop

count = 0
while (count<9):
  print('The count is:',count)
  count=count+1
print("Example of while loop")

In [ ]:
#Example of while looop

i=1
while(i<=10):
  print("Even numbers",2*i)
  i=i+1

print("First ten even numbers")



In [ ]:
#Program to print even number from 1 to 10
count=1
while(count<=10):
  if(count%2==0):
    print("Even number",count)
  count=count+1

In [ ]:
#Program to check if the number is less than 5
count=0
while(count<5):
  print(count,"is less than 5")
  count=count+1
else:
  print(count,"is not less than 5")

0 is less than 5
1 is less than 5
2 is less than 5
3 is less than 5
4 is less than 5
5 is not less than 5


In [ ]:
#Single statement suites
#Infinite loop
flag=1
while(flag): print("Helloworld")

In [ ]:
#Example of for loop

#for letter in "Python":
#  print('Current letter is:',letter)

fruits=['Banana','Apple','Mango']
for fruit in fruits:
  print('Current fruit is :',fruit)

print("Example of for loop")

Current fruit is : Banana
Current fruit is : Apple
Current fruit is : Mango
Example of for loop


In [ ]:
fruits=['Banana','Apple','Mango']
for index in range(len(fruits)):
  print('Current fruit :', fruits[index])
print("Example with sequence index")

Current fruit : Banana
Current fruit : Apple
Current fruit : Mango
Example with sequence index


#Date: 08june2022
Here we are learning about python function and how to use different function in python.


In [ ]:
'''Date: 06/08/2022
</> Navee'''
#Defining function
def sum():
  num1=int(input("Enter first number :"))
  num2=int(input("Enter second number :"))
  sum=num1+num2
  return sum
#Calling sum() function in print statement

s=sum() 
'''Here we are calling the function and storing the return value in 
variable'''
print("The sum is :",s)

Enter first number :5
Enter second number :4
The sum is : 9


In [ ]:
#Program to delete function
def delfun():
  print("Hello dummy")
delfun()
#Here we are deleting the function
del delfun()

#Lambda Function
A function doesn't need to have a name. A lambda expression in Python allows us to create anonymous python function, and we use the 'lambda' keyword for it.
The following is the syntax for a lambda expression.
lambda arguments: expression

- It's worth noting that it can have any number of arguments. but only one expressionn. It evaluates the value of that expression, and returns the result.

In [ ]:
'''Lambda function
Date: 08june2022
</> Navee'''
print("Example of lambda function")
print("*************************")
#Defining function
myvar= lambda a,b:(a*b)+2

#calling lambda function
print("\n\nThe lambda function evaluated :",myvar(3,5))

print("\n\nEnd of the program")
print("******************")

Example of lambda function
*************************


The lambda function evaluated : 17


End of the program
******************


In [ ]:
#Program using lambda function
'''Lambda function
</> Navee '''
print("Program for (a+b)² ")
print("*******************")
#Defining function
result= lambda a,b:((a*a)+(b*b)+(2*a*b))
#calling lambda function
print("\n\nThe lambda function evaluated :",result(2,3))
print("\n\nEnd of the program")
print("******************")

Program for (a+b)² 
*******************


The lambda function evaluated : 25


End of the program
******************


#Recursive function
When a function calls itself that is called recursion


In [ ]:
'''Recursive function
</> Navee '''

#defining function
def factorial(x):
  #Recursive function to find factorial of a number
  if x==1:
    return 1
  else:
    return (x*factorial(x-1))

num=int(input("Enter number to find factorial :"))
#Function calling
print("The factorial of",num,"is",factorial(num))

In [ ]:
#Program to print the fibonacci series using recursion
#</> Navee
#Defining function
print("Program for printing fibonacci series")
print("*************************************")
def fibonacci(n):
  if n<=1:
    return (n)
  else:
    return(fibonacci(n-1)+fibonacci(n-2))

nTerms=int(input("Enter number of terms :"))
if nTerms<=0:
  print("Invalid input ! Please input a positive integer")
else:
  print("Fibonacci series:")
for i in range(nTerms):
  #function calling
  print(fibonacci(i))

Enter number of terms :10
Fibonacci series:
0
1
1
2
3
5
8
13
21
34




```
# This is formatted as code
```

#Date: 10june2022

Python string functions- consecutive sequence of characters is known as string

In [ ]:
#Program for string function
str="Kendriya"
#To access the first string
print(str[0])
#To access the fourth character of the string
print(str[3])
#To access the last character of the string
print(str[-1])
#To access the third last character of the string
print(str[-3])
#To print the first few characters from the string
print(str[0:3])

K
d
a
i
Ken


-Positive subscript helps in accessing the string from the beginning.
-Negative subscript helps in accessing the string from the end.

In [ ]:
#Python creating and intitializing strings


print("Ama\"s fri")

-In this example backslash(\) voids the initial function and hence we can use special charaters as well.

In [ ]:
#String traversal using for loop
A="Mi Amor"
for i in A:
  print(i)

In [ ]:
#String traversal using while loop
A="Mon cherie"
q=len(A)
i=0
while i<q:
  print(A[i])
  i=i+1

In [ ]:
#Operator in string
str="JIMS"
str1="Vasant kunj"

'''1 -Concatenation - operator joins the text on both sides of the operator'''
print(str+str1)

'''2 -Repetition - operator the string on the left hand side times the value on 
right hand side'''
print(3*str)

JIMSVasant kunj
JIMSJIMSJIMS


In [ ]:
#Python strings opertions
'''3 - in(Membership) - operator displays 1 if the string, contains the given
charcter pr the sequence of characters'''
str="Bonjour"
'B' in str
'Se' in str

'''4 - not in  - operator displays 1 if the string does not contain the given
character or the sequence of characters''' 
"B" not in str

False

In [ ]:
#Python string operations
str="Hari OM Hari OM"

#Optional slicing according to the query
print(str[2:])
print(str[:4])
#Negative indexing
print(str[-1:])
print(str[:-1])

#for i in range(0,10,2):print(str[i])

ri OM Hari OM
Hari
M
Hari OM Hari O


In [ ]:
#Built in function
'''len() -returns the length of the string'''
str="save EArth"
print(len(str))

'''Capatilize function -Returns the exact copy of the string with the first 
letter in the upper case'''
print(str.capitalize())

'''find(sub(substring which we want to find),start,end) 
-Function is used to search the first occurence of the substring
in the given string, It returns the index at which the substring starts. It returns -1
if the substring does occur in the string.'''

#Code for find function
str.find('sa')
''' - On omitting the start parameters, the function starts the search from the
beginning'''
str.find('A',1,9)

'''Displays -1 because the susbstring could not be found between the given
parameters''' 

10
Save earth


'Displays -1 because the susbstring could not be found between the given\nparameters'

In [ ]:
#Built-in function

'''1- isalnum() -returns true is the string contains only letters and
digit. It returns false if the string contains any special character
like _,@,#'''
'''2- isalpha() -Returns true if the string contains only letters
otherwise return false'''
'''3- isdigit() -Returns true if the string contains only numbers 
otherwise it returns false'''

str="key"
str.isdigit()
#'Str1earht'.isalnum()

False

#Date: 13june2022

In [ ]:
'''Program for palindrome.
Date: 13june2022
</> Navee'''

def palin():
  str=input("Enter the string :")
  l=len(str)
  p=l-1
  index=0
  while(index<p):
    if(str[index]==str[p]):
      index=index+1
      p=p-1 
    else:
      print("String is not a palindrome")
      break
  else:
      print("String is a palindrome")
palin()


Enter the string :madam
String is a palindrome


In [ ]:
'''Program for string count in python
Date: 13June2022
</>Navee'''

def lettercount():
  word='pineapple'
  count=0
  for letter in word:
    if letter=='e':
      count=count+1
  print(count)
lettercount()

2


In [ ]:
#Program to count character and spaces in a given string
'''Date:13june2022
</>Navee'''
def letcount():
  str=input("Enter string: ")
  space=0
  count=0
  for letter in str:
    if letter==' ':
      space=space+1
    if letter.isalpha():
      count=count+1
  print("Number of spaces are :",space)
  print("Number of characters are :",count)
letcount()

In [ ]:
#Program to find string in the end or in the beginning using meta character

def find():
  import re
  string1='SitaRam'
  if re.search('Ram$',string1):
    print("String found")
  else:
    print("No match")
find()

String found


#Date: 14June2022
RegEx Module - Is a sequence of characters that forms a search pattern
- RegEx can be used to check if a string contains the specified search pattern

#Findall() function
- The findall() function returns a list containing all matches.

In [ ]:
'''Program using re module
date:14june2022
</> Navee'''
import re

txt = "The rain in Spain"

#Check if "Portugal" is in the string:

x = re.findall("Portugal", txt)
print(x)

if (x):
  print("Yes, there is at least one match!")
else:
  print("No match")


[]
No match


#Search() function
The search() function searches the string for a match, and returns a Match object if there is a match.

In [ ]:
'''Program using re module
date:14june2022
</> Navee'''
import re
#Check if the string starts with "The" and ends with "Spain":

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)

if x:
  print("YES! We have a match!")
else:
  print("No match")

YES! We have a match!


In [ ]:
'''Program using re module
date:14june2022
</> Navee'''
import re

txt = "The rain in Spain"
x = re.search("\s", txt)

print("The first white-space character is located in position:", x.start())

The first white-space character is located in position: 3


#Split() expression
- The split() function returns a list where the string has been split at each match:

In [ ]:
'''Program using re module
date:14june2022
</> Navee'''
import re
#Split the string at every white-space character:
txt="The rain in Spain"
x=re.split("\s",txt)
print(x)

['The', 'rain', 'in', 'Spain']


In [ ]:
'''Program using re module
date:14june2022
</> Navee'''
import re
#Split the string only at the first occurence
txt="The rain in Spain"
x=re.split("\s",txt,1)
print(x)

['The', 'rain in Spain']


#Sub() function
- Sub() function replaces the matches with the text of your choice

In [ ]:
'''Program using re module
date:14june2022
</> Navee'''

import re
#Replace every white-space character with the number 9:
txt= "The rain in Spain"
x=re.sub("\s","9",txt)
print(x)

The9rain9in9Spain


You can control the number of replacements by specifying the count parameter.

In [ ]:
'''Program using re module
date:14june2022
</> Navee'''
import re
#Replace the first 2 occurences
txt="The rain in Spain"
x=re.sub("\s","9",txt,2)
print(x)

The9rain9in Spain


#Match object 
A match object is an object containing information about the search and the result.

In [ ]:
'''Program using re module
date:14june2022
</> Navee'''

import re
#Do a search that will return a Match object
txt="The rain in Spain"
x=re.search("ai",txt)
print(x) #This will print an object


<re.Match object; span=(5, 7), match='ai'>


#Date:16june2022

Started using numpy module


In [ ]:
''' Program using numpy library 
</> Navee 
Using the basic commands from NumPy '''

import numpy
arr=numpy.array([[1,2,3,4],[6,7,8,9]])
ar=numpy.array((1,2,3,4)) #Tuple to create a NumPy array
print(arr) #Printing array
print(arr[0,1]) #Printing element from 2d array
print(ar) #Printing tuple as array
a=type(arr) 
print(a) #Used to fetch datatype
print(arr.ndim) #Used to tell the dimension of the array
print(arr.dtype)

print(numpy.__version__) #Command to get the version of numpy


[[1 2 3 4]
 [6 7 8 9]]
2
[1 2 3 4]
<class 'numpy.ndarray'>
2
int64
1.21.6


In [ ]:
#Program to access array elements
#</> Navee
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])  #Using + to add two array elements

print(arr[0]+arr[3])  #Using + to add two array elements

7
5


In [ ]:
#Program creating 3-D array elements 
'''To access elements from 3-D arrrays we can use comma separated integers
representing the dimensions and the index of the element'''
#</> Navee
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape) #Used to get to know the shape of the array

print(arr[1,0,2]) #Accessing element in 3-D array

(2, 2, 3)
9


In [ ]:
#Program using negative indexing
#</> Navee
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])
print('Last element from 2nd dim : 'arr[0,-1])

4


In [ ]:
#Program to get the data type of an array object
#</> Navee
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
#Program to get the data type of an array object
#</> Navee
import numpy as np
arr=np.array(['delhi','Mumbai'])
print(arr.dtype) #String data type is represented as U6

<U6


In [ ]:
#Program to create an array with data type string
#</> Navee
import numpy as np
arr=np.array([1,2,3,4],dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#Program to create an array with data type 4bytes string
#</> Navee
import numpy as np
arr=np.array([1,2,3,4],dtype='i4') 
#Defining size of the array with i4 (int32)
 
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [ ]:
#Program to change data type from float to integer by using 'i' as parameter value
#</> Navee
import numpy as np
arr=np.array([1.1,2.2,3.3,4.9])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [ ]:
#Program to change data type from float to integer by using int as parameter value
#</> Navee
import numpy as np
arr=np.array([1.1,2.2,3.3,4.4])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int64


In [ ]:
#Program to change data type from integer to boolean
#</> Navee
import numpy as np
arr=np.array([1,2,3,4])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True  True]
bool


#Date:17june2022

File handling in python


In [ ]:
f=open("file:///C:/Users/bca/Desktop/BCA2021Navee/Python/File%20handling/file.txt")
print(f.read())

''' 
Program to fetch file in gocolab

from google.colab import drive

drive.mount("/content/gdrive")

from IPython.display import Image
'''

FileNotFoundError: ignored